# Generated by Django 3.2.9 on 2021-12-25 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20211226_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cl', models.IntegerField()),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=100, verbose_name='Имя')),
                ('middlename', models.CharField(max_length=100, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиент',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cor', models.IntegerField()),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Курсы',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Dgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_g', models.IntegerField()),
                ('id_cl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.client', verbose_name='Клиент')),
                ('id_cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группа',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_t', models.IntegerField()),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=100, verbose_name='Имя')),
                ('middlename', models.CharField(max_length=100, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватель',
            },
        ),
        migrations.RemoveField(
            model_name='cameras',
            name='type',
        ),
        migrations.RemoveField(
            model_name='videocameras',
            name='maxResolution',
        ),
        migrations.DeleteModel(
            name='ActionCameras',
        ),
        migrations.DeleteModel(
            name='Cameras',
        ),
        migrations.DeleteModel(
            name='MaxResolution',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='VideoCameras',
        ),
        migrations.AddField(
            model_name='dgroup',
            name='id_t',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.teacher', verbose_name='Преподаватель'),
        ),
    ]
