# Generated by Django 3.2.9 on 2021-12-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20211226_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id_cor',
            field=models.IntegerField(verbose_name='ID'),
        ),
    ]
