# Generated by Django 3.2.9 on 2021-12-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_course_id_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_cl',
            field=models.IntegerField(verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='dgroup',
            name='id_g',
            field=models.IntegerField(verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id_t',
            field=models.IntegerField(verbose_name='ID'),
        ),
    ]
